version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/mnt/c/Users/imam/AppData/Local/Docker/wsl/data
    ports:
      - 5432:5432
    
    environment:
      - POSTGRES_DB=testDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080